GolfCard.MVC/Models/Player.cs
using System;

namespace GolfCard.MVC.Models
{
    public class Player
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }
}

GolfCard.MVC/Models/Response.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GolfCard.MVC.Models
{
    public class Response
    {
        public string Error { get; set; }
        public string Message { get; set; }
    }
}

GolfCard.MVC/Models/ScoreCard.cs
using Foolproof;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GolfCard.MVC.Models
{
    public class ScoreCardView
    {
        public Guid Id { get; set; }
        public string Player { get; set; }
        [RequiredIfTrue("Player")]
        public List<int> Hole { get; set; }
        public int IN_1 { get; set; }
        public int IN_2 { get; set; }
        public int OUT { get; set; }
        public int HandiCap { get; set; }
        public int NET { get; set; }
    }
}

GolfCard.MVC/Models/StableFord.cs
using Foolproof;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GolfCard.MVC.Models
{
    public class StableFord
    {
        public Guid Id { get; set; }
        public string Player { get; set; }
        [RequiredIfTrue("Player")]
        public List<int> Hole { get; set; }
        public List<int> Points { get; set; }
        public int IN { get; set; }
        public int OUT { get; set; }
        public int TOT { get; set; }
        public int HandiCap { get; set; }
        public int NET { get; set; }
        public int StableFordsPoints { get; set; }
    }
}

GolfCard.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GolfCard.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GolfCard.MVC/Controllers/ScoreCardController.cs
using GolfCard.Core.Business_Logic;
using GolfCard.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using GolfCard.Core;
using GolfCard.MVC.Mapper;
using GolfCard.SqlClient.DTO;

namespace GolfCard.MVC.Controllers
{
    public class ScoreCardController : Controller
    {
        private GolfScoreCardLogic _golfScoreCardLogic;
        private GolfScoreMapper _golfScoreMapper;
        public ScoreCardController()
        {
            _golfScoreCardLogic = new GolfScoreCardLogic();
            _golfScoreMapper = new GolfScoreMapper();
        }
        // GET: ScoreCard
        public ActionResult ViewScoreCard()
        {

            var scores = _golfScoreCardLogic.GetScores();
            var scoreboard = _golfScoreMapper.MapToScoreCardView(scores);
            return View(scoreboard);
        }

        public ActionResult ViewStableScoring()
        {

            var scores = _golfScoreCardLogic.GetScores();
            var scoreboard = _golfScoreMapper.CalculatePointsAndMap(scores);
            return View(scoreboard);
        }

        public ActionResult CreateCard()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCard(IList<ScoreCardView> scorecard)
        {
            IEnumerable<Game> scores = new List<Game>();

            var playerScores = scorecard.Where(p => p.Player != null).Where(s => !s.Hole.Contains(0)).ToList();

            if (playerScores.Any())
            {
                scores = _golfScoreCardLogic.WorkOutScore(_golfScoreMapper.MapToGameModel(playerScores)).Result;
                _golfScoreCardLogic.SaveScores(scores);

                var scoreboard = _golfScoreMapper.MapToScoreCardView(scores);

                return RedirectToAction("ViewScoreCard", scoreboard);
            }
            else
            {
                ViewBag.ErrorMessage = "The scorecard contains invalid entries.\nPlease insert a player name and all the shots before clicking on the SUBMIT button.";
                return View();
            }                      
        }

        public ActionResult EditCard(Guid Id)
        {
            var player = _golfScoreCardLogic.GetGameById(Id);
            var scoreboard = (_golfScoreMapper.MapToScoreCardView(new List<Game>() { player }));
            return View(scoreboard.FirstOrDefault());
        }

        public ActionResult DeleteCard(Guid Id)
        {
            var player = _golfScoreCardLogic.GetGameById(Id);
            var scoreboard = (_golfScoreMapper.MapToScoreCardView(new List<Game>() { player }));
            return View(scoreboard.FirstOrDefault());
        }

        [HttpPost]
        public ActionResult EditCard(ScoreCardView scoreCardView)
        {
            if (scoreCardView.Player != null && !scoreCardView.Hole.Contains(0))
            {
                var scores = _golfScoreCardLogic.WorkOutScore(_golfScoreMapper.MapToGameModel(new List<ScoreCardView>() { scoreCardView })).Result;
                _golfScoreCardLogic.EditScores(scores.FirstOrDefault());
                return RedirectToAction("ViewScoreCard");
            }
            else
            {
                ViewBag.ErrorMessage = "The scorecard contains invalid entries.\nPlease insert all the shots before clicking on the SUBMIT button.";
                return View();
            }            
        }

        [HttpPost]
        public ActionResult DeleteCard(ScoreCardView scoreCardView)
        {
            try
            {
                _golfScoreCardLogic.DeleteScores(scoreCardView.Id);
                return RedirectToAction("ViewScoreCard");
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = $"Error occurered while deleting the score \n {ex}";
                return View();
            }
        }
    }
}

GolfCard.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GolfCard.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GolfCard.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

GolfCard.MVC/Views/ScoreCard/CreateCard.cshtml
@model IList<GolfCard.MVC.Models.ScoreCardView>

@{
    ViewBag.Title = "CreateCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    input {
        width: 26px;
    }

    .nameTextColumn {
        width: 170px;
    }
</style>

<h2>Score Card</h2>
<br/>
<p class="alert-danger">
    @ViewBag.ErrorMessage
</p>
<br/>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <table class="table table-bordered">
        <tr>
            <th>
                HOLES
            </th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
            <th>7</th>
            <th>8</th>
            <th>9</th>
            <th>IN</th>
            <th>10</th>
            <th>11</th>
            <th>12</th>
            <th>13</th>
            <th>14</th>
            <th>15</th>
            <th>16</th>
            <th>17</th>
            <th>18</th>
            <th>OUT</th>
            <th>TOTAL</th>
            <th>HANDICAP</th>
            <th>NET</th>
        </tr>
        <tr>
            <th>
                YARDS
            </th>
            <th>365</th>
            <th>423</th>
            <th>230</th>
            <th>463</th>
            <th>421</th>
            <th>210</th>
            <th>522</th>
            <th>407</th>
            <th>465</th>
            <th>3421</th>
            <th>537</th>
            <th>375</th>
            <th>168</th>
            <th>358</th>
            <th>395</th>
            <th>425</th>
            <th>513</th>
            <th>375</th>
            <th>510</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        <tr>
            <th>
                PAR
            </th>
            <th>4</th>
            <th>4</th>
            <th>3</th>
            <th>4</th>
            <th>4</th>
            <th>4</th>
            <th>3</th>
            <th>5</th>
            <th>4</th>
            <th>39</th>
            <th>4</th>
            <th>5</th>
            <th>4</th>
            <th>3</th>
            <th>4</th>
            <th>4</th>
            <th>4</th>
            <th>5</th>
            <th>4</th>
            <th>33</th>
            <th>72</th>
            <th></th>
            <th>72</th>
        </tr>
        @for (int i = 0; i < 5; i++)
        {
            <tr>
                <td>
                    @Html.TextBoxFor(x => x[i].Player, new { @class = "nameTextColumn" })
                </td>
                @for (int j = 0; j < 18; j++)
                {
                    <td>
                        @Html.TextBoxFor(x => x[i].Hole)
                    </td>

                    if (j == 9)
                    {
                        <td>
                            @Html.DisplayFor(x => x[i].IN)
                        </td>
                    }
                }
                <td>
                    @Html.DisplayFor(x => x[i].OUT)
                </td>
                <td>
                    @Html.DisplayFor(x => x[i].TOT)
                </td>
                <td>
                    @Html.TextBoxFor(x => x[i].HandiCap)
                </td>
                <td></td>
            </tr>
        }
    </table>
    <br/>
    <p class="alert-info">
        Make sure each entry has a Player Name and Score for every hole indexed 1 to 18. Any imcomplete entry will be ignored. 
    </p>
    <button class="btn btn-primary">
        Calculate Scores
    </button>
}

GolfCard.MVC/Views/ScoreCard/DeleteCard.cshtml
@model GolfCard.MVC.Models.ScoreCardView

@{
    ViewBag.Title = "DeleteCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DeleteCard</h2>
<br />
<p class="alert-danger">
    @ViewBag.ErrorMessage
</p>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <table class="table table-bordered">
        <tr>
            <th>
                HOLES
            </th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
            <th>7</th>
            <th>8</th>
            <th>9</th>
            <th>IN</th>
            <th>10</th>
            <th>11</th>
            <th>12</th>
            <th>13</th>
            <th>14</th>
            <th>15</th>
            <th>16</th>
            <th>17</th>
            <th>18</th>
            <th>OUT</th>
            <th>TOTAL</th>
            <th>HANDICAP</th>
            <th>NET</th>
        </tr>
        <tr>
            <th>
                YARDS
            </th>
            <th>365</th>
            <th>423</th>
            <th>230</th>
            <th>463</th>
            <th>421</th>
            <th>210</th>
            <th>522</th>
            <th>407</th>
            <th>465</th>
            <th>3421</th>
            <th>537</th>
            <th>375</th>
            <th>168</th>
            <th>358</th>
            <th>395</th>
            <th>425</th>
            <th>513</th>
            <th>375</th>
            <th>510</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        <tr>
            <th>
                PAR
            </th>
            <th>4</th>
            <th>4</th>
            <th>3</th>
            <th>4</th>
            <th>4</th>
            <th>4</th>
            <th>3</th>
            <th>5</th>
            <th>4</th>
            <th>39</th>
            <th>4</th>
            <th>5</th>
            <th>4</th>
            <th>3</th>
            <th>4</th>
            <th>4</th>
            <th>4</th>
            <th>5</th>
            <th>4</th>
            <th>33</th>
            <th>72</th>
            <th></th>
            <th>72</th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Player)
            </td>
            @for (int i = 0; i < 18; i++)
            {
                if (i == 9)
                {
                    <td>
                        @Html.DisplayFor(model => model.IN)
                    </td>
                }
                <td>
                    @Html.DisplayFor(model => model.Hole[i])
                </td>
            }
            <td>
                @Html.DisplayFor(model => model.OUT)
            </td>
            <td>
                @Html.DisplayFor(model => model.TOT)
            </td>
            <td>
                @Html.DisplayFor(model => model.HandiCap)
            </td>
            <td>
                @Html.DisplayFor(model => model.NET)
            </td>
            <td></td>
        </tr>
    </table>
    <br />
    <p class="alert-info">
        Make sure each entry has a Player Name and Score for every hole indexed 1 to 18. Any imcomplete entry will be ignored.
    </p>

    <button class="btn btn-danger">
       Delete Score
    </button>
}

GolfCard.MVC/Views/ScoreCard/EditCard.cshtml
@model GolfCard.MVC.Models.ScoreCardView

@{
    ViewBag.Title = "EditCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    input {
        width: 30px;
    }

    .nameTextColumn {
        width: 170px;
    }
</style>

<h2>Edit Card</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <table class="table table-bordered">
        <tr>
            <th>
                HOLES
            </th>
            <th>1</th>
            <th>2</th>
            <th>3</th>
            <th>4</th>
            <th>5</th>
            <th>6</th>
            <th>7</th>
            <th>8</th>
            <th>9</th>
            <th>IN</th>
            <th>10</th>
            <th>11</th>
            <th>12</th>
            <th>13</th>
            <th>14</th>
            <th>15</th>
            <th>16</th>
            <th>17</th>
            <th>18</th>
            <th>OUT</th>
            <th>TOTAL</th>
            <th>HANDICAP</th>
            <th>NET</th>
        </tr>
        <tr>
            <th>
                YARDS
            </th>
            <th>365</th>
            <th>423</th>
            <th>230</th>
            <th>463</th>
            <th>421</th>
            <th>210</th>
            <th>522</th>
            <th>407</th>
            <th>465</th>
            <th>3421</th>
            <th>537</th>
            <th>375</th>
            <th>168</th>
            <th>358</th>
            <th>395</th>
            <th>425</th>
            <th>513</th>
            <th>375</th>
            <th>510</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        <tr>
            <th>
                PAR
            </th>
            <th>4</th>
            <th>4</th>
            <th>3</th>
            <th>4</th>
            <th>4</th>
            <th>4</th>
            <th>3</th>
            <th>5</th>
            <th>4</th>
            <th>39</th>
            <th>4</th>
            <th>5</th>
            <th>4</th>
            <th>3</th>
            <th>4</th>
            <th>4</th>
            <th>4</th>
            <th>5</th>
            <th>4</th>
            <th>33</th>
            <th>72</th>
            <th></th>
            <th>72</th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Player)
            </td>
           @for (int j = 0; j < 18; j++)
           {
                <td>
                    @Html.EditorFor(model => model.Hole[j])
                    @Html.ValidationMessageFor(model => model.Hole[j], "", new { @class = "text-danger" })
                </td>

                if (j == 9)
                {
                    <td>
                    </td>
                }
            }
            <td>
            </td>
            <td>
            </td>
            <td>
                @Html.TextBoxFor(x => x.HandiCap)
            </td>
            <td>
            </td>
        </tr>
    </table>
    <br />
    <p class="alert-info">
        Make sure each entry has a Player Name and Score for every hole indexed 1 to 18. Any imcomplete entry will be ignored.
    </p>
    <button class="btn btn-primary">
        Calculate Scores
    </button>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GolfCard.MVC/Views/ScoreCard/ViewScoreCard.cshtml
@model IEnumerable<GolfCard.MVC.Models.ScoreCardView>

@{
    ViewBag.Title = "ViewScoreCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .nameTextColumn {
        width: 170px;
    }

    .btn a {
        color: white;
        text-decoration: none;
    }

    .btn a:hover {
        color: white;
        text-decoration: none;
    }
</style>

<h2>Previous Golf Scores</h2>

<br />
<br/>
<table class="table table-bordered">
    <tr>
        <th>
            HOLES
        </th>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>IN</th>
        <th>10</th>
        <th>11</th>
        <th>12</th>
        <th>13</th>
        <th>14</th>
        <th>15</th>
        <th>16</th>
        <th>17</th>
        <th>18</th>
        <th>OUT</th>
        <th>TOTAL</th>
        <th>HANDICAP</th>
        <th>NET</th>
        <th></th>
    </tr>
    <tr>
        <th>
            YARDS
        </th>
        <th>365</th>
        <th>423</th>
        <th>230</th>
        <th>463</th>
        <th>421</th>
        <th>210</th>
        <th>522</th>
        <th>407</th>
        <th>465</th>
        <th>3421</th>
        <th>537</th>
        <th>375</th>
        <th>168</th>
        <th>358</th>
        <th>395</th>
        <th>425</th>
        <th>513</th>
        <th>375</th>
        <th>510</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <tr>
        <th>
            PAR
        </th>
        <th>4</th>
        <th>4</th>
        <th>3</th>
        <th>4</th>
        <th>4</th>
        <th>4</th>
        <th>3</th>
        <th>5</th>
        <th>4</th>
        <th>39</th>
        <th>4</th>
        <th>5</th>
        <th>4</th>
        <th>3</th>
        <th>4</th>
        <th>4</th>
        <th>4</th>
        <th>5</th>
        <th>4</th>
        <th>33</th>
        <th>72</th>
        <th></th>
        <th>72</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Player, new { @class = "nameTextColumn" })
            </td>
            @foreach (var modelitem in item.Hole.Take(9))
                {
                <td>
                    @Html.DisplayFor(m => modelitem)
                </td>
            }
            <td>
                @Html.DisplayFor(modelItem => item.IN_1)
            </td>
            @foreach (var modelitem in item.Hole.Skip(9).Take(9))
                {
                <td>
                    @Html.DisplayFor(m => modelitem)
                </td>
            }
            <td>
                @Html.DisplayFor(modelItem => item.IN_2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OUT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HandiCap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NET)
            </td>
            <td style="width:126px">
                @Html.ActionLink("Edit", "EditCard", new { id = item.Id }) | @Html.ActionLink("Delete", "DeleteCard", new { id = item.Id })
            </td>
        </tr>
    }
</table>

<button class="btn btn-primary ">
    @Html.ActionLink("Create New Score Card", "CreateCard")
</button>

GolfCard.MVC/Views/ScoreCard/ViewStableScoring.cshtml
@model IEnumerable<GolfCard.MVC.Models.StableFord>

@{
    ViewBag.Title = "ViewStableScoring";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
   .btn a {
        color: white;
        text-decoration: none;
    }

    .btn a:hover {
        color: white;
        text-decoration: none;
    }
</style>

<h2>StableFord Points</h2>
<br />
<br />
<table class="table table-striped">
    <tr>
        <th>
            HOLES
        </th>
        <th>1</th>
        <th>2</th>
        <th>3</th>
        <th>4</th>
        <th>5</th>
        <th>6</th>
        <th>7</th>
        <th>8</th>
        <th>9</th>
        <th>IN</th>
        <th>10</th>
        <th>11</th>
        <th>12</th>
        <th>13</th>
        <th>14</th>
        <th>15</th>
        <th>16</th>
        <th>17</th>
        <th>18</th>
        <th>OUT</th>
        <th>TOTAL</th>
        <th>HANDICAP</th>
        <th>NET</th>
        <th></th>
    </tr>
    <tr>
        <th>
            YARDS
        </th>
        <th>365</th>
        <th>423</th>
        <th>230</th>
        <th>463</th>
        <th>421</th>
        <th>210</th>
        <th>522</th>
        <th>407</th>
        <th>465</th>
        <th>3421</th>
        <th>537</th>
        <th>375</th>
        <th>168</th>
        <th>358</th>
        <th>395</th>
        <th>425</th>
        <th>513</th>
        <th>375</th>
        <th>510</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <tr>
        <th>
            PAR
        </th>
        <th>4</th>
        <th>4</th>
        <th>3</th>
        <th>4</th>
        <th>4</th>
        <th>4</th>
        <th>3</th>
        <th>5</th>
        <th>4</th>
        <th>39</th>
        <th>4</th>
        <th>5</th>
        <th>4</th>
        <th>3</th>
        <th>4</th>
        <th>4</th>
        <th>4</th>
        <th>5</th>
        <th>4</th>
        <th>33</th>
        <th>72</th>
        <th></th>
        <th>72</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var inPoints = 0;
        var outPoints = 0;
        var totPoints = 0;

        <tr>
            <th>
                @Html.DisplayFor(modelItem => item.Player, new { @class = "nameTextColumn" })
            </th>
             @foreach (var modelitem in item.Hole.Take(9))
                {
                <td>
                    @Html.DisplayFor(m => modelitem)
                </td>
            }
            <td>
                @Html.DisplayFor(modelItem => item.IN)
            </td>
            @foreach (var modelitem in item.Hole.Skip(9).Take(9))
                {
                <td>
                    @Html.DisplayFor(m => modelitem)
                </td>
            }
            <td>
                @Html.DisplayFor(modelItem => item.OUT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TOT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HandiCap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NET)
            </td>
            <td style="width:126px">
                @Html.ActionLink("Edit", "EditCard", new { Id = item.Id }) | @Html.ActionLink("Delete", "DeleteCard", new { Id = item.Id })
            </td>
        </tr>
        <tr>
            <td>
                Stableford points
            </td>
            @foreach (var modelitem in item.Points.Take(9))
                {
                <td>
                    @Html.DisplayFor(m => modelitem)
                </td>

                inPoints += modelitem;
            }
            <td>
                @inPoints
            </td>
            @foreach (var modelitem in item.Points.Skip(9).Take(9))
                {
                <td>
                    @Html.DisplayFor(m => modelitem)
                </td>

                outPoints += modelitem;
            }
            <td>
                @(totPoints = inPoints + outPoints)
            </td>
            <td></td>
            <td></td>
            <td>
                @Html.DisplayFor(modelItem => item.StableFordsPoints)
            </td>
            <td></td>
        </tr>
    }
</table>

<button class="btn btn-primary">
    @Html.ActionLink("Create New Score Card", "CreateCard")
</button>

GolfCard.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Golf Scoring application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Score Board", "CreateCard", "ScoreCard")</li>
                    <li>@Html.ActionLink("Previous Scores", "ViewScoreCard", "ScoreCard")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>